### ISSUE TITLE
部署logto后，创建web应用时，会大概率发生错误

### ISSUE THREAD

**Issue by overhood** [CloudNativeGame/aigc-gateway#17]
首次部署完logoto，打开首页，创建root账号，然后创建web应用，会大概率（几乎100%）发生错误。

![image](https://github.com/CloudNativeGame/aigc-gateway/assets/2291358/481a4c3b-627c-4fcf-9a69-56b4781c3cb4)

 at https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:61147
    at new Promise (<anonymous>)
    at r (https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:61053)
    at c._fetch (https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:56192)
    at async i (https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:50996)
    at async a.<computed> [as json] (https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:51903)
    at async https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:2783145
    at async https://logto-admin.c55fb5feab13d4cd2bedc00cd1268eb91.ap-northeast-1.alicontainer.com/console/index.4348ad5c.js:5:340258

**Comment by chrisliu1995** [comment]
若使用自签证书，需要注意在浏览器访问时，对logto域名以及logto-admin域名点击信任。这里出现的原因是浏览器还没有授予logto域名的访问权限。
